name: End-to-end tests 🧪
on: [push]
jobs:
  cypress-run:
    runs-on: ubuntu-20.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      # Install NPM dependencies, cache them correctly
      # and run all Cypress tests
      - name: Cypress run
        uses: cypress-io/github-action@v2
      # Command to upload screenshots to Argos
      - name: Upload screenshots to argos-ci.com
        uses: npx @argos-ci/cli cypress/screenshots